language: c
compiler: gcc

before_install:
  - git submodule update --init --recursive
  - make test
  - sudo pip install cpp-coveralls
script:
  - ./test
after_success:
  - coveralls --exclude test.c --exclude chi.h --exclude data --exclude libtap --gcov-options '\-lp'
